### ISSUE TITLE
release process?

### ISSUE THREAD

**Issue by uninsane** [System64fumo/sysvol#1]
i've been running sysvol on my devices for a couple months, it's been really stable and i love it! with the latest Makefile refactor you made, the [nix packaging](https://git.uninsane.org/colin/nix-files/src/commit/5e7a05c18326a01653e7260d1e2524e33a0d6fe5/pkgs/additional/sysvol/default.nix) for this looks really clean now, and if i submitted that to nixpkgs i think it would be accepted.

the one thing lacking which is nice to have in this context is some notion of "official" releases. just a way for OS maintainers to look at a package and see if it's up to date, and if not to know which commit to update it to. there's a lot of different ways to do that: two easy ways are to use the "releases" tab in Github, or use native git tags, like `git tag v0.2.3 && git push origin v0.2.3`.

so, if you'd like to have some NixOS users, consider tagging a release :)

**Comment by System64fumo** [comment]
Glad to hear you enjoying sysvol!

Personally i'm not too keen on "releases" if that's how you put it.
I'm more of a fan of the rolling release model.

I'd be down to make a major binary release every major or important update.
But if i do it would probably use date/timestamps, eg: ver 24-06-09

Please let me know if that sounds good.

**Comment by uninsane** [comment]
date tags are fine for this 👍

if you'd really prefer to avoid tagging anything at all, i could setup the NixOS package to just track the latest commit to main, only it makes things a little more chaotic because without tags we might accidentally update to a commit that's halfway through a big refactor and wasn't ever meant to be deployed. but if your development style is to always keep `main` clean, then packaging it that way would be fine too.

**Comment by System64fumo** [comment]
I tend to make sure every update i push out builds fine without any issues, at worst i will disable a feature temporarily until the new code is in place (this doesn't happen often)

**Comment by uninsane** [comment]
ok, i'll write up the package to just track main, so don't worry about the tags.

is sysvol released under any license? if not i have to put "unfree" in the license field.

**Comment by System64fumo** [comment]
Uhh it doesn't really have a license. _yet_
If it's important i can pick a license later today.

**Comment by uninsane** [comment]
it's not critical, i think the most significant impact is that some of the tooling can't work with unlicensed code for legal reasons, so it won't show up in caches (which isn't a big deal for projects like this which build so quickly), and it might mean that it doesn't get run in our CI jobs, not sure.

**Comment by System64fumo** [comment]
Honestly i would pick something like [this](https://en.wikipedia.org/wiki/WTFPL) though i doubt nix supports that kind of license.

In a nutshell, i'm fine with people copying my code and doing whatever with it.

**Comment by uninsane** [comment]
we actually have 42 packages under the WTFPL license right now 😆

do you want me to put that in the license field then?

**Comment by System64fumo** [comment]
By all means go ahead!

**Comment by uninsane** [comment]
ok, i'll close this then. thanks for helping me sort out the packaging details! i submitted it to nixpkgs [here](https://github.com/NixOS/nixpkgs/pull/318440).
