### ISSUE TITLE
[hyprland] layerrule ignorezero not working

### ISSUE THREAD

**Issue by shadowelite-sec** [System64fumo/sysvol#3]
i am using this rule but blur not working with  ignorezero 

```
# sysvol
layerrule = blur,sysvol
layerrule = ignorezero,sysvol 

```
without ignorezero

![image](https://github.com/System64fumo/sysvol/assets/54718375/12acdfab-929b-4e83-93e6-e00fce91433b)

with ignorezero
![image](https://github.com/System64fumo/sysvol/assets/54718375/ca1517a5-0adb-4178-a735-8ea315577311)

 please fix

**Comment by System64fumo** [comment]
I personally use: `layerrule = ignorealpha 0.25, sysvol`
Try adjusting the value until it works properly for you

**Comment by shadowelite-sec** [comment]
> I personally use: `layerrule = ignorealpha 0.25, sysvol` Try adjusting the value until it works properly for you

It's not changing anything. The same result occurs for every value. Sysvol is becoming completely transparent. Is this something to do with CSS?"

**Comment by System64fumo** [comment]
Ah you simply don't have a background for the main box

Usually it's set with this
```
revealer > * {
    background: something;
}
```

Assuming you're not using the revealer try changing
```
window {
    background: transparent;
}
```
To a different color

I should probably give the main box a css name to avoid such case...

**Comment by System64fumo** [comment]
@shadowelite-sec [this commit](https://github.com/System64fumo/sysvol/commit/9cfea9647ede40f26e691849974891bcfb00b375) should fix it.
Try now?

**Comment by shadowelite-sec** [comment]
> @shadowelite-sec [this commit](https://github.com/System64fumo/sysvol/commit/9cfea9647ede40f26e691849974891bcfb00b375) should fix it. Try now?

Awesome, it's working now, 
Thank you so much

**Comment by System64fumo** [comment]
Sweet, Happy to help!
