### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by shadowelite-sec** [System64fumo/sysvol#4]
Hey me again :smile: 

Just wanted to say a big thanks for this awesome project. It's been super helpful for me, and I really appreciate all the work you've done on it.

#### Suggestions:

* 1.  Implement mic action indications, such as mic volume levels and mute status.

* 2. Introduce gradient color change based on volume level. It would be beneficial if this feature could be toggled and if users could specify the minimum, maximum, and mid-range values using arguments.(because of  `pamixer --allow-boost`).
 
 * 3.  While we can already specify the position, it would be helpful to have the option to specify an exact location or to add margins for left, right, top, and bottom positions separate.

* 4. This suggestion isn't directly related to the current project, but I'd love to see a similar program for controlling screen brightness. Could you consider developing one?

I hope you'll take these suggestions into account. Once again, thank you for your hard work!

**Comment by shadowelite-sec** [comment]
> Thanks for the suggestions!
> 
> Adding a volume input indicator is a great idea, I think i can do that but it might take some time.
> 
> As for gradient colors, I think i can just add a class called .volume-%%% with 10 different values .volume-0 to .volume-100
> 
> Specifying minimum and maximum volume levels should be easy to implement, Will take a look at that shortly.
> 
> Exact position control might be annoying to add, I hope it's possible to add with how layer shell works.
> 
> I've been considering rebranding this program as syshud and include brightness stuff or caps/num lock stuff Buuuuut that might be a bit of a stretch, I could just add it and see how it goes from there though.

The gradient color is related to the volume's min and max values. If the volume increases, the gradient color intensifies; if the volume decreases, the gradient color saturation decreases accordingly.

**Comment by System64fumo** [comment]
Understood, the way you'd do that would be like this:
```
.volume-10 scale highlight {
    background: linear-gradient(90deg, rgba(112,193,255,1) 0%, rgba(0,144,255,1) 100%);
    opacity: 0.1
}
```

And then increase the opacity with each number

Also as for min-max values
Isn't that determined by you?
As in, the way you would change the volume level, eg: `wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ -l 1.0`

Now that i think about it, I'm not sure i understood how you want me to implement a min/max
I can totally do that ui wise
But wouldn't it function just fine right now?

**Comment by System64fumo** [comment]
Okay i think [this](https://github.com/System64fumo/sysvol/commit/245524fc7684a9713f8c12c5cb51ddb66b781451) should do it, I did away with the whole .volume-%% thing, instead now it uses names.

Here's an example: (Throw this at the bottom of your css for it to work)

```
/* Volume states */
.overamplified scale highlight {
	background: Red;
}
.high scale highlight {
	background: MediumSeaGreen;
}
.medium scale highlight {
	background: LightSeaGreen;
}
.low scale highlight {
	background: Teal;
}
.muted scale highlight {
	background: SeaGreen;
}
.muted-blocking scale highlight {
	background: Black;
}
```

**Comment by System64fumo** [comment]
Hopefully i didn't break everything with this major update :crossed_fingers:
[This one](https://github.com/System64fumo/sysvol/commit/2e38ae6d3aaf0d8955189dfafc0059c74a313ab5) "should" add more control over the position and layout of sysvol
Let me know if anything broke.

**Comment by shadowelite-sec** [comment]
> Hopefully i didn't break everything with this major update 🤞 [This one](https://github.com/System64fumo/sysvol/commit/2e38ae6d3aaf0d8955189dfafc0059c74a313ab5) "should" add more control over the position and layout of sysvol Let me know if anything broke.

exactly what i wanted thankyou

However, there seems to be an issue with the margin (-m) property. It only works when the position is set to top, and even then, only the first argument of the margin (-m 100) is applied.

#### command
`./sysvol -p top -o h -m 100 600`

#### output
![Thursday_24_2024_10_21_45_AM](https://github.com/System64fumo/sysvol/assets/54718375/d9377a49-e0b4-47a0-8d47-d3c0a29057cf)

**Comment by System64fumo** [comment]
You're supposed to wrap it with "" as shown in the readme
The argument is read as a single string not all trailing arguments past -m

eg: sysvol -m "10 0 0 0" ect

**Comment by shadowelite-sec** [comment]
> You're supposed to wrap it with "" as shown in the readme The argument is read as a single string not all trailing arguments past -m
> 
> eg: sysvol -m "10 0 0 0" ect
> 
> Also i'm unsure about it not working if it's not set to top It should work?

Sorry, my mistake. It's working like a charm. Thank you so much! I hope you implement other features too

**Comment by System64fumo** [comment]
Just checked again, confirmed working.

sysvol -p "bottom" -m "0 0 100 0"

Though i wouldn't recommend using these margins to space the module away from the screen as it moves the whole overlay away and thus the revealer animation might not look right.
Use css if you want to make it float (as shown in the example css)

**Comment by System64fumo** [comment]
And with [this](https://github.com/System64fumo/sysvol/commit/be9a1a9290dac0f2bd2c959b4ff4a187e1198622) commit sysvol now supports microphones!
(Tho it's pipewire only, i don't really care about pulse so unless someone specifically asks for it or i get bored enough i won't bother with it)

Please let me know what you think

**Comment by shadowelite-sec** [comment]
> And with [this](https://github.com/System64fumo/sysvol/commit/be9a1a9290dac0f2bd2c959b4ff4a187e1198622) commit sysvol now supports microphones! (Tho it's pipewire only, i don't really care about pulse so unless someone specifically asks for it or i get bored enough i won't bother with it)
> 
> Please let me know what you think

cool, working perfectly ! , 
its time to delete my `volume.sh` :smile: 
waiting for brightness control

**Comment by System64fumo** [comment]
Ho boy.. brightness..
Yeaaah maybe next week
Too much work to rebrand this project
It was just added to nix os repos not that long ago
I'm hoping it won't bother the person who added it :grimacing:

**Comment by shadowelite-sec** [comment]
> Ho boy.. brightness.. Yeaaah maybe next week Too much work to rebrand this project It was just added to nix os repos not that long ago I'm hoping it won't bother the person who added it 😬
> 
> Alternatively i could create a new project? Idk? At the end of the day i plan to merge all of my projects into 1 to reduce resource usage and such So i don't mind creating a different independent project just for brightness/capslock/numlock/scrolllock/ect indicators
> 
> Tell me what you think

I think it would be better to add all of this into one repo. It will be easier to install, and from a user perspective, it’s simpler to install one package instead of several different ones.

Plus, we can add more features like keyboard backlight control (similar to GNOME).

Take your time. I'm always happy to test. :smile:

**Comment by shadowelite-sec** [comment]
one issue 
![image](https://github.com/System64fumo/sysvol/assets/54718375/6a4fb988-69fa-4d6d-a5d5-393d43fd6b79)

program crashing when i change device (connect to bluetooth headset)

**Comment by System64fumo** [comment]
> one issue ![image](https://private-user-images.githubusercontent.com/54718375/339495142-6a4fb988-69fa-4d6d-a5d5-393d43fd6b79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMDEzNjcsIm5iZiI6MTcxODMwMTA2NywicGF0aCI6Ii81NDcxODM3NS8zMzk0OTUxNDItNmE0ZmI5ODgtNjlmYS00ZDZkLWE1ZDUtMzkzZDQzZmQ2Yjc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDE3NTEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiYmQ3YjRlMDAyZjUyNjUzZDcwMzJjY2FmOGVjY2IxNzJjZTQyMWQ1YjQ5ZWQ0MzhjM2E2ODk2NjIyZTdjZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PYGi54T2RBShPoJdP_rH6PvMLsKz5wh_f6x8387I1Io)
> 
> program crashing when i change device (connect to bluetooth headset)

Thaat ill have to look into
I'd prefer you open a new issue for that

**Comment by System64fumo** [comment]
> > Ho boy.. brightness.. Yeaaah maybe next week Too much work to rebrand this project It was just added to nix os repos not that long ago I'm hoping it won't bother the person who added it 😬
> > Alternatively i could create a new project? Idk? At the end of the day i plan to merge all of my projects into 1 to reduce resource usage and such So i don't mind creating a different independent project just for brightness/capslock/numlock/scrolllock/ect indicators
> > Tell me what you think
> 
> I think it would be better to add all of this into one repo. It will be easier to install, and from a user perspective, it’s simpler to install one package instead of several different ones.
> 
> Plus, we can add more features like keyboard backlight control (similar to GNOME).
> 
> Take your time. I'm always happy to test. 😄

As for this, i'd like to hear @uninsane's opinion on that
I'm hoping it won't be too much trouble to rename the project in nixos

Like it just got added and now it's getting a rebrand

If it's too much trouble i'm fine with it staying as sysvol
But hopefully by next week it "should" (if i'm not lazy) become syshud

**Comment by uninsane** [comment]
@System64fumo projects get renamed all the time, we're used to that & it's not much trouble on my end.

as for consolidating everything into one repository, also not an issue. i've seen it where each component of the repo gets its own directory and Makefile and we package each component individually even though it's part of the same "project" ([Buffyboard/Unl0kr](https://gitlab.com/postmarketOS/buffybox) is an example of that), or where it's just a toplevel Makefile/build script and we ship a single package for everything in the repo (e.g. `coreutils`, `busybox`, etc). i don't think distros tend to have a strong preference toward any specific approach here, just do whatever you prefer.

on the topic of backlight display, notifiers, etc: i don't have any strong opinions for or against it. not something i need, but not something that would get in my way either.

**Comment by uninsane** [comment]
re-reading @shadowelite-sec's post, [SwayOSD](https://github.com/ErikReider/SwayOSD) might be worth a look. i don't use it, because rather than monitor the system volume like sysvol does, SwayOSD requires you to route all volume changes through it. but by doing that it's able to support notifiers, brightness, and those other things pretty easily.

**Comment by shadowelite-sec** [comment]
> re-reading @shadowelite-sec's post, [SwayOSD](https://github.com/ErikReider/SwayOSD) might be worth a look. i don't use it, because rather than monitor the system volume like sysvol does, SwayOSD requires you to route all volume changes through it. but by doing that it's able to support modifiers like caps lock, brightness, and those other things pretty easily.

Yeah, I have tried SwayOSD, but it didn't work well for me.  personally really liked this project, simple and very easy to configure

**Comment by System64fumo** [comment]
@shadowelite-sec So regarding the brightness related stuff,
You said "but I'd love to see a similar program for controlling screen brightness"

sysvol doesn't control your volume, It just monitors changes and displays them.
I assume that's how you'd like me to implement brightness stuff correct?

**Comment by System64fumo** [comment]
[Done](https://github.com/System64fumo/sysvol/commit/d957f08e30939f9ebf18c8322563c78953171124).

Let me know if this works for you.
Gonna.. have to clean up the code behind this..
I highly discourage you from taking a look, It's a mess (that works)

**Comment by shadowelite-sec** [comment]
> [Done](https://github.com/System64fumo/sysvol/commit/d957f08e30939f9ebf18c8322563c78953171124).
> 
> Let me know if this works for you. Gonna.. have to clean up the code behind this.. I highly discourage you from taking a look, It's a mess (that works)

its working bro :+1:  but its it possible to set a different position for brightness (like : left -> volume, right -> brightness, etc)

**Comment by System64fumo** [comment]
Idk i feel like that would be "too" much if you catch my drift.

Unless you meant for something like an icon_on_start sorta deal that changes both at the same time.

Still feel like that would be a bit "too much" but it would be more reasonable.

Alternatively if and whenever i get to adding css names for the brightness stuff just hide the icons and do whatever from css.

**Comment by shadowelite-sec** [comment]
> Idk i feel like that would be "too" much if you catch my drift.
> 
> Unless you meant for something like an icon_on_start sorta deal that changes both at the same time.
> 
> Still feel like that would be a bit "too much" but it would be more reasonable.
> 
> Alternatively if and whenever i get to adding css names for the brightness stuff just hide the icons and do whatever from css.

oh ok , no problem

**Comment by shadowelite-sec** [comment]
Can you tell me what the CSS class names for this are?

**Comment by System64fumo** [comment]
Have not added yet but they will be similar to how the volume ones work.
