### ISSUE TITLE
program crashes when the output device changes

### ISSUE THREAD

**Issue by shadowelite-sec** [System64fumo/sysvol#5]
one issue 
![image](https://github.com/System64fumo/sysvol/assets/54718375/6a4fb988-69fa-4d6d-a5d5-393d43fd6b79)

program crashing when i change device (connect to bluetooth headset)

_Originally posted by @shadowelite-sec in https://github.com/System64fumo/sysvol/issues/4#issuecomment-2166439665_

**Comment by System64fumo** [comment]
Humm there seems to be an issue when switching output devices, Might take a while to figure out.

**Comment by shadowelite-sec** [comment]
> Humm there seems to be an issue when switching output devices, Might take a while to figure out.

no problems

**Comment by System64fumo** [comment]
Okay i'm praying that with [this](https://github.com/System64fumo/sysvol/commit/78e0634eb4b5a6d1a02c040c709545960625704f) audio devices should be set properly
Prior to this the default audio device was stuck at whatever you had when you first launched sysvol
Now it should change dynamically (Excluding audio input, that still needs to be fixed later)

I wasn't exactly able to reproduce your crash but i narrowed it down to it just using invalid audio device stuff
I did however get it to crash if i removed my USB sound card while it was the default audio output, It doesn't do that anymore so hopefully that fixes it for you too.

Please let me know,
Test feedback is highly appreciated.

**Comment by shadowelite-sec** [comment]
I think it's fixed. Closing for now. Thanks.
